/* ================================================
   Style Loader for PDF Generation
   Concatenates all CSS for injection into HTML
   ================================================ */

import pagedStyles from './pagedStyles.css?raw';
import componentStyles from './componentStyles.css?raw';

/**
 * Load all CSS styles for PDF generation
 * @returns Concatenated CSS string
 */
export function loadStyles(): string {
  return `
/* ================================================
   M&M 3e Character Sheet PDF Styles
   Generated by mm3e-builder
   ================================================ */

${pagedStyles}

${componentStyles}
  `.trim();
}

/**
 * Get only Paged.js specific styles
 * @returns Paged.js CSS rules
 */
export function loadPagedStyles(): string {
  return pagedStyles;
}

/**
 * Get only component styles
 * @returns Component CSS rules
 */
export function loadComponentStyles(): string {
  return componentStyles;
}
