import type { TFunction } from 'i18next';
import {
  ADVANTAGE_DEFS,
  MODIFIER_DEFS,
  POWER_DEFS,
  SKILL_DEFS,
} from '../entities/gameDataLoaders';
import type { ExportLabels, GameDataRefs } from './excelGenerator';

export function buildExcelLabels(t: TFunction): ExportLabels {
  return {
    sheetSummary: t('excel.sheetSummary'),
    sheetAbilities: t('excel.sheetAbilities'),
    sheetDefenses: t('excel.sheetDefenses'),
    sheetSkills: t('excel.sheetSkills'),
    sheetAdvantages: t('excel.sheetAdvantages'),
    sheetPowers: t('excel.sheetPowers'),
    sheetComplications: t('excel.sheetComplications'),
    sheetEquipment: t('excel.sheetEquipment'),
    sheetOffense: t('excel.sheetOffense'),
    sheetNotes: t('excel.sheetNotes'),
    heroName: t('header.heroName'),
    player: t('header.player'),
    identity: t('header.identity'),
    identityTypeLabel: t('header.identityType.secret').split(' ')[0],
    base: t('header.base'),
    powerLevel: t('header.powerLevel'),
    heroPoints: t('header.heroPoints'),
    powerPoints: t('header.powerPoints'),
    gender: t('header.gender'),
    age: t('header.age'),
    height: t('header.height'),
    weight: t('header.weight'),
    eyes: t('header.eyes'),
    hair: t('header.hair'),
    groupAffiliation: t('header.groupAffiliation'),
    series: t('header.series'),
    gameMaster: t('header.gameMaster'),
    abilityNames: {
      str: t('abilities.str'),
      sta: t('abilities.sta'),
      agl: t('abilities.agl'),
      dex: t('abilities.dex'),
      fgt: t('abilities.fgt'),
      int: t('abilities.int'),
      awe: t('abilities.awe'),
      pre: t('abilities.pre'),
    },
    defenseNames: {
      dodge: t('defenses.dodge'),
      parry: t('defenses.parry'),
      fortitude: t('defenses.fortitude'),
      will: t('defenses.will'),
    },
    colName: t('excel.colName'),
    colRanks: t('excel.colRanks'),
    colAbility: t('excel.colAbility'),
    colTotal: t('excel.colTotal'),
    colCost: t('excel.colCost'),
    colDescription: t('excel.colDescription'),
    colEffect: t('excel.colEffect'),
    colModifiers: t('excel.colModifiers'),
    colNotes: t('excel.colNotes'),
    colBonus: t('excel.colBonus'),
    colRange: t('excel.colRange'),
    colTitle: t('excel.colTitle'),
    colType: t('excel.colType'),
    colAlternateEffects: t('excel.colAlternateEffects'),
    section: t('excel.section'),
    spent: t('excel.spent'),
    remaining: t('excel.remaining'),
    totalSpent: t('excel.totalSpent'),
    absent: t('excel.absent'),
    dynamic: t('excel.dynamic'),
    removable: t('excel.removable'),
    easilyRemovable: t('excel.easilyRemovable'),
    descriptors: t('excel.descriptors'),
    yes: t('excel.yes'),
    no: t('excel.no'),
  };
}

export function buildExcelGameDataRefs(): GameDataRefs {
  return {
    powerDefs: POWER_DEFS,
    modifierDefs: MODIFIER_DEFS,
    advantageDefs: ADVANTAGE_DEFS,
    skillDefs: SKILL_DEFS,
  };
}
